import { chromium } from 'playwright'
const errors = []
const browser = await chromium.launch()
const page = await browser.newPage()
page.on('pageerror', (e) => errors.push('PAGEERROR: ' + e.message))
page.on('console', (m) => { if (m.type() === 'error') errors.push('CONSOLE: ' + m.text()) })
await page.goto('http://localhost:4600/', { waitUntil: 'networkidle', timeout: 20000 })
await page.waitForTimeout(1500)
const appHtml = await page.$eval('#app', (el) => el.innerHTML.length).catch(() => 0)
console.log('#app innerHTML length:', appHtml)
const iconErr = errors.filter((e) => /is not a function|createLucideIcon|at-sign/.test(e))
console.log('icon/factory errors:', iconErr.length ? iconErr : 'NONE')
console.log('total errors:', errors.length)
errors.slice(0, 8).forEach((e) => console.log('  -', e.slice(0, 160)))
await browser.close()
