import { callRpc } from '@/utils/supabase-rpc'
import { z } from 'zod'

/**
 * A contact's phone numbers.
 *
 * `contacts.phone` remains the primary number — the directory search, the inbox
 * panel and every existing read still go through it — and `contact_phones` is
 * the complete set, position 0 being that primary. Both are written by one
 * statement pair inside `public.set_contact_phones`, so they cannot drift: a
 * client that wrote the table directly would leave a contact with no numbers if
 * its second call failed.
 */
const contactPhoneSchema = z.object({
  id: z.string(),
  phone: z.string(),
  /** `public.phone_digits(phone)`, generated by the database. */
  digits: z.string(),
  position: z.number(),
})

export type ContactPhone = z.infer<typeof contactPhoneSchema>

/** Matches the cap enforced by `public.set_contact_phones`. */
export const MAX_CONTACT_PHONES = 10

export async function listContactPhones({
  workspaceId,
  contactId,
}: {
  workspaceId: string
  contactId: string
}): Promise<Array<ContactPhone>> {
  return callRpc(
    'list_contact_phones',
    { p_workspace_id: workspaceId, p_contact_id: contactId },
    z.array(contactPhoneSchema),
  )
}

/**
 * Replaces the whole set, order significant. Duplicate spellings of one number
 * collapse in the database rather than here, so the rule is enforced once.
 */
export async function setContactPhones({
  workspaceId,
  contactId,
  phones,
}: {
  workspaceId: string
  contactId: string
  phones: Array<string>
}): Promise<Array<ContactPhone>> {
  return callRpc(
    'set_contact_phones',
    {
      p_workspace_id: workspaceId,
      p_contact_id: contactId,
      p_phones: phones.slice(0, MAX_CONTACT_PHONES),
    },
    z.array(contactPhoneSchema),
  )
}
