/**
 * @generated by `astryx theme build` — do not edit manually.
 * Source: src\themes\gothic\gothicTheme.ts
 * Command: astryx theme build src\themes\gothic\gothicTheme.ts --out src\themes\gothic\theme.css
 * Generated: 2026-07-28T08:58:26.665Z
 */

import type { DefinedTheme } from '@astryxdesign/core/theme';
import type { IconRegistry } from '@astryxdesign/core/Icon';
export declare const gothicIconRegistry: IconRegistry;
export declare const gothicTheme: DefinedTheme;
