/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SignUpRouteImport } from './routes/sign-up'
import { Route as SignInRouteImport } from './routes/sign-in'
import { Route as PasswordResetRouteImport } from './routes/password-reset'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as AuthenticatedIndexRouteImport } from './routes/_authenticated/index'
import { Route as AuthenticatedProfileRouteImport } from './routes/_authenticated/profile'
import { Route as AuthenticatedWorkspacesIndexRouteImport } from './routes/_authenticated/workspaces/index'
import { Route as AuthenticatedOnboardingIndexRouteImport } from './routes/_authenticated/onboarding/index'
import { Route as AuthenticatedWorkspacesCreateRouteImport } from './routes/_authenticated/workspaces/create'
import { Route as AuthenticatedWorkspacesIdIndexRouteImport } from './routes/_authenticated/workspaces/$id/index'
import { Route as AuthenticatedWorkspacesIdTeamsRouteImport } from './routes/_authenticated/workspaces/$id/teams'
import { Route as AuthenticatedWorkspacesIdSettingsRouteImport } from './routes/_authenticated/workspaces/$id/settings'
import { Route as AuthenticatedWorkspacesIdProjectsRouteImport } from './routes/_authenticated/workspaces/$id/projects'
import { Route as AuthenticatedWorkspacesIdMembersRouteImport } from './routes/_authenticated/workspaces/$id/members'

const SignUpRoute = SignUpRouteImport.update({
  id: '/sign-up',
  path: '/sign-up',
  getParentRoute: () => rootRouteImport,
} as any)
const SignInRoute = SignInRouteImport.update({
  id: '/sign-in',
  path: '/sign-in',
  getParentRoute: () => rootRouteImport,
} as any)
const PasswordResetRoute = PasswordResetRouteImport.update({
  id: '/password-reset',
  path: '/password-reset',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedIndexRoute = AuthenticatedIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedProfileRoute = AuthenticatedProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedWorkspacesIndexRoute =
  AuthenticatedWorkspacesIndexRouteImport.update({
    id: '/workspaces/',
    path: '/workspaces/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedOnboardingIndexRoute =
  AuthenticatedOnboardingIndexRouteImport.update({
    id: '/onboarding/',
    path: '/onboarding/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedWorkspacesCreateRoute =
  AuthenticatedWorkspacesCreateRouteImport.update({
    id: '/workspaces/create',
    path: '/workspaces/create',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedWorkspacesIdIndexRoute =
  AuthenticatedWorkspacesIdIndexRouteImport.update({
    id: '/workspaces/$id/',
    path: '/workspaces/$id/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedWorkspacesIdTeamsRoute =
  AuthenticatedWorkspacesIdTeamsRouteImport.update({
    id: '/workspaces/$id/teams',
    path: '/workspaces/$id/teams',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedWorkspacesIdSettingsRoute =
  AuthenticatedWorkspacesIdSettingsRouteImport.update({
    id: '/workspaces/$id/settings',
    path: '/workspaces/$id/settings',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedWorkspacesIdProjectsRoute =
  AuthenticatedWorkspacesIdProjectsRouteImport.update({
    id: '/workspaces/$id/projects',
    path: '/workspaces/$id/projects',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedWorkspacesIdMembersRoute =
  AuthenticatedWorkspacesIdMembersRouteImport.update({
    id: '/workspaces/$id/members',
    path: '/workspaces/$id/members',
    getParentRoute: () => AuthenticatedRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof AuthenticatedIndexRoute
  '/password-reset': typeof PasswordResetRoute
  '/sign-in': typeof SignInRoute
  '/sign-up': typeof SignUpRoute
  '/profile': typeof AuthenticatedProfileRoute
  '/workspaces/create': typeof AuthenticatedWorkspacesCreateRoute
  '/onboarding/': typeof AuthenticatedOnboardingIndexRoute
  '/workspaces/': typeof AuthenticatedWorkspacesIndexRoute
  '/workspaces/$id/members': typeof AuthenticatedWorkspacesIdMembersRoute
  '/workspaces/$id/projects': typeof AuthenticatedWorkspacesIdProjectsRoute
  '/workspaces/$id/settings': typeof AuthenticatedWorkspacesIdSettingsRoute
  '/workspaces/$id/teams': typeof AuthenticatedWorkspacesIdTeamsRoute
  '/workspaces/$id/': typeof AuthenticatedWorkspacesIdIndexRoute
}
export interface FileRoutesByTo {
  '/password-reset': typeof PasswordResetRoute
  '/sign-in': typeof SignInRoute
  '/sign-up': typeof SignUpRoute
  '/profile': typeof AuthenticatedProfileRoute
  '/': typeof AuthenticatedIndexRoute
  '/workspaces/create': typeof AuthenticatedWorkspacesCreateRoute
  '/onboarding': typeof AuthenticatedOnboardingIndexRoute
  '/workspaces': typeof AuthenticatedWorkspacesIndexRoute
  '/workspaces/$id/members': typeof AuthenticatedWorkspacesIdMembersRoute
  '/workspaces/$id/projects': typeof AuthenticatedWorkspacesIdProjectsRoute
  '/workspaces/$id/settings': typeof AuthenticatedWorkspacesIdSettingsRoute
  '/workspaces/$id/teams': typeof AuthenticatedWorkspacesIdTeamsRoute
  '/workspaces/$id': typeof AuthenticatedWorkspacesIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/password-reset': typeof PasswordResetRoute
  '/sign-in': typeof SignInRoute
  '/sign-up': typeof SignUpRoute
  '/_authenticated/profile': typeof AuthenticatedProfileRoute
  '/_authenticated/': typeof AuthenticatedIndexRoute
  '/_authenticated/workspaces/create': typeof AuthenticatedWorkspacesCreateRoute
  '/_authenticated/onboarding/': typeof AuthenticatedOnboardingIndexRoute
  '/_authenticated/workspaces/': typeof AuthenticatedWorkspacesIndexRoute
  '/_authenticated/workspaces/$id/members': typeof AuthenticatedWorkspacesIdMembersRoute
  '/_authenticated/workspaces/$id/projects': typeof AuthenticatedWorkspacesIdProjectsRoute
  '/_authenticated/workspaces/$id/settings': typeof AuthenticatedWorkspacesIdSettingsRoute
  '/_authenticated/workspaces/$id/teams': typeof AuthenticatedWorkspacesIdTeamsRoute
  '/_authenticated/workspaces/$id/': typeof AuthenticatedWorkspacesIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/password-reset'
    | '/sign-in'
    | '/sign-up'
    | '/profile'
    | '/workspaces/create'
    | '/onboarding/'
    | '/workspaces/'
    | '/workspaces/$id/members'
    | '/workspaces/$id/projects'
    | '/workspaces/$id/settings'
    | '/workspaces/$id/teams'
    | '/workspaces/$id/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/password-reset'
    | '/sign-in'
    | '/sign-up'
    | '/profile'
    | '/'
    | '/workspaces/create'
    | '/onboarding'
    | '/workspaces'
    | '/workspaces/$id/members'
    | '/workspaces/$id/projects'
    | '/workspaces/$id/settings'
    | '/workspaces/$id/teams'
    | '/workspaces/$id'
  id:
    | '__root__'
    | '/_authenticated'
    | '/password-reset'
    | '/sign-in'
    | '/sign-up'
    | '/_authenticated/profile'
    | '/_authenticated/'
    | '/_authenticated/workspaces/create'
    | '/_authenticated/onboarding/'
    | '/_authenticated/workspaces/'
    | '/_authenticated/workspaces/$id/members'
    | '/_authenticated/workspaces/$id/projects'
    | '/_authenticated/workspaces/$id/settings'
    | '/_authenticated/workspaces/$id/teams'
    | '/_authenticated/workspaces/$id/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  PasswordResetRoute: typeof PasswordResetRoute
  SignInRoute: typeof SignInRoute
  SignUpRoute: typeof SignUpRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sign-up': {
      id: '/sign-up'
      path: '/sign-up'
      fullPath: '/sign-up'
      preLoaderRoute: typeof SignUpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sign-in': {
      id: '/sign-in'
      path: '/sign-in'
      fullPath: '/sign-in'
      preLoaderRoute: typeof SignInRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/password-reset': {
      id: '/password-reset'
      path: '/password-reset'
      fullPath: '/password-reset'
      preLoaderRoute: typeof PasswordResetRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/': {
      id: '/_authenticated/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/profile': {
      id: '/_authenticated/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof AuthenticatedProfileRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/workspaces/': {
      id: '/_authenticated/workspaces/'
      path: '/workspaces'
      fullPath: '/workspaces/'
      preLoaderRoute: typeof AuthenticatedWorkspacesIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/onboarding/': {
      id: '/_authenticated/onboarding/'
      path: '/onboarding'
      fullPath: '/onboarding/'
      preLoaderRoute: typeof AuthenticatedOnboardingIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/workspaces/create': {
      id: '/_authenticated/workspaces/create'
      path: '/workspaces/create'
      fullPath: '/workspaces/create'
      preLoaderRoute: typeof AuthenticatedWorkspacesCreateRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/workspaces/$id/': {
      id: '/_authenticated/workspaces/$id/'
      path: '/workspaces/$id'
      fullPath: '/workspaces/$id/'
      preLoaderRoute: typeof AuthenticatedWorkspacesIdIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/workspaces/$id/teams': {
      id: '/_authenticated/workspaces/$id/teams'
      path: '/workspaces/$id/teams'
      fullPath: '/workspaces/$id/teams'
      preLoaderRoute: typeof AuthenticatedWorkspacesIdTeamsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/workspaces/$id/settings': {
      id: '/_authenticated/workspaces/$id/settings'
      path: '/workspaces/$id/settings'
      fullPath: '/workspaces/$id/settings'
      preLoaderRoute: typeof AuthenticatedWorkspacesIdSettingsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/workspaces/$id/projects': {
      id: '/_authenticated/workspaces/$id/projects'
      path: '/workspaces/$id/projects'
      fullPath: '/workspaces/$id/projects'
      preLoaderRoute: typeof AuthenticatedWorkspacesIdProjectsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/workspaces/$id/members': {
      id: '/_authenticated/workspaces/$id/members'
      path: '/workspaces/$id/members'
      fullPath: '/workspaces/$id/members'
      preLoaderRoute: typeof AuthenticatedWorkspacesIdMembersRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
  }
}

interface AuthenticatedRouteChildren {
  AuthenticatedProfileRoute: typeof AuthenticatedProfileRoute
  AuthenticatedIndexRoute: typeof AuthenticatedIndexRoute
  AuthenticatedWorkspacesCreateRoute: typeof AuthenticatedWorkspacesCreateRoute
  AuthenticatedOnboardingIndexRoute: typeof AuthenticatedOnboardingIndexRoute
  AuthenticatedWorkspacesIndexRoute: typeof AuthenticatedWorkspacesIndexRoute
  AuthenticatedWorkspacesIdMembersRoute: typeof AuthenticatedWorkspacesIdMembersRoute
  AuthenticatedWorkspacesIdProjectsRoute: typeof AuthenticatedWorkspacesIdProjectsRoute
  AuthenticatedWorkspacesIdSettingsRoute: typeof AuthenticatedWorkspacesIdSettingsRoute
  AuthenticatedWorkspacesIdTeamsRoute: typeof AuthenticatedWorkspacesIdTeamsRoute
  AuthenticatedWorkspacesIdIndexRoute: typeof AuthenticatedWorkspacesIdIndexRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedProfileRoute: AuthenticatedProfileRoute,
  AuthenticatedIndexRoute: AuthenticatedIndexRoute,
  AuthenticatedWorkspacesCreateRoute: AuthenticatedWorkspacesCreateRoute,
  AuthenticatedOnboardingIndexRoute: AuthenticatedOnboardingIndexRoute,
  AuthenticatedWorkspacesIndexRoute: AuthenticatedWorkspacesIndexRoute,
  AuthenticatedWorkspacesIdMembersRoute: AuthenticatedWorkspacesIdMembersRoute,
  AuthenticatedWorkspacesIdProjectsRoute:
    AuthenticatedWorkspacesIdProjectsRoute,
  AuthenticatedWorkspacesIdSettingsRoute:
    AuthenticatedWorkspacesIdSettingsRoute,
  AuthenticatedWorkspacesIdTeamsRoute: AuthenticatedWorkspacesIdTeamsRoute,
  AuthenticatedWorkspacesIdIndexRoute: AuthenticatedWorkspacesIdIndexRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  PasswordResetRoute: PasswordResetRoute,
  SignInRoute: SignInRoute,
  SignUpRoute: SignUpRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
