/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SignUpRouteImport } from './routes/sign-up'
import { Route as SignInRouteImport } from './routes/sign-in'
import { Route as PasswordResetRouteImport } from './routes/password-reset'
import { Route as OnboardingRouteImport } from './routes/onboarding'
import { Route as InstagramCallbackRouteImport } from './routes/instagram-callback'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as AuthenticatedIndexRouteImport } from './routes/_authenticated/index'
import { Route as AuthenticatedSettingsRouteImport } from './routes/_authenticated/settings'
import { Route as AuthenticatedProfileRouteImport } from './routes/_authenticated/profile'
import { Route as AuthenticatedWorkspacesIndexRouteImport } from './routes/_authenticated/workspaces/index'
import { Route as AuthenticatedSettingsIndexRouteImport } from './routes/_authenticated/settings/index'
import { Route as AuthenticatedSettingsSecurityRouteImport } from './routes/_authenticated/settings/security'
import { Route as AuthenticatedSettingsProfileRouteImport } from './routes/_authenticated/settings/profile'
import { Route as AuthenticatedSettingsNotificationsRouteImport } from './routes/_authenticated/settings/notifications'
import { Route as AuthenticatedSettingsAppearanceRouteImport } from './routes/_authenticated/settings/appearance'
import { Route as AuthenticatedWorkspacesIdIndexRouteImport } from './routes/_authenticated/workspaces/$id/index'
import { Route as AuthenticatedWorkspacesIdSettingsRouteImport } from './routes/_authenticated/workspaces/$id/settings'
import { Route as AuthenticatedWorkspacesIdInboxRouteImport } from './routes/_authenticated/workspaces/$id/inbox'
import { Route as AuthenticatedWorkspacesIdContactsRouteImport } from './routes/_authenticated/workspaces/$id/contacts'
import { Route as AuthenticatedWorkspacesIdSettingsIndexRouteImport } from './routes/_authenticated/workspaces/$id/settings/index'
import { Route as AuthenticatedWorkspacesIdInboxIndexRouteImport } from './routes/_authenticated/workspaces/$id/inbox/index'
import { Route as AuthenticatedWorkspacesIdSettingsMembersRouteImport } from './routes/_authenticated/workspaces/$id/settings/members'
import { Route as AuthenticatedWorkspacesIdInboxConversationIdRouteImport } from './routes/_authenticated/workspaces/$id/inbox/$conversationId'
import { Route as AuthenticatedWorkspacesIdSettingsChannelsIndexRouteImport } from './routes/_authenticated/workspaces/$id/settings/channels/index'
import { Route as AuthenticatedWorkspacesIdSettingsChannelsNewRouteImport } from './routes/_authenticated/workspaces/$id/settings/channels/new'

const SignUpRoute = SignUpRouteImport.update({
  id: '/sign-up',
  path: '/sign-up',
  getParentRoute: () => rootRouteImport,
} as any)
const SignInRoute = SignInRouteImport.update({
  id: '/sign-in',
  path: '/sign-in',
  getParentRoute: () => rootRouteImport,
} as any)
const PasswordResetRoute = PasswordResetRouteImport.update({
  id: '/password-reset',
  path: '/password-reset',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const InstagramCallbackRoute = InstagramCallbackRouteImport.update({
  id: '/instagram-callback',
  path: '/instagram-callback',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedIndexRoute = AuthenticatedIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedSettingsRoute = AuthenticatedSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedProfileRoute = AuthenticatedProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedWorkspacesIndexRoute =
  AuthenticatedWorkspacesIndexRouteImport.update({
    id: '/workspaces/',
    path: '/workspaces/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedSettingsIndexRoute =
  AuthenticatedSettingsIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedSettingsRoute,
  } as any)
const AuthenticatedSettingsSecurityRoute =
  AuthenticatedSettingsSecurityRouteImport.update({
    id: '/security',
    path: '/security',
    getParentRoute: () => AuthenticatedSettingsRoute,
  } as any)
const AuthenticatedSettingsProfileRoute =
  AuthenticatedSettingsProfileRouteImport.update({
    id: '/profile',
    path: '/profile',
    getParentRoute: () => AuthenticatedSettingsRoute,
  } as any)
const AuthenticatedSettingsNotificationsRoute =
  AuthenticatedSettingsNotificationsRouteImport.update({
    id: '/notifications',
    path: '/notifications',
    getParentRoute: () => AuthenticatedSettingsRoute,
  } as any)
const AuthenticatedSettingsAppearanceRoute =
  AuthenticatedSettingsAppearanceRouteImport.update({
    id: '/appearance',
    path: '/appearance',
    getParentRoute: () => AuthenticatedSettingsRoute,
  } as any)
const AuthenticatedWorkspacesIdIndexRoute =
  AuthenticatedWorkspacesIdIndexRouteImport.update({
    id: '/workspaces/$id/',
    path: '/workspaces/$id/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedWorkspacesIdSettingsRoute =
  AuthenticatedWorkspacesIdSettingsRouteImport.update({
    id: '/workspaces/$id/settings',
    path: '/workspaces/$id/settings',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedWorkspacesIdInboxRoute =
  AuthenticatedWorkspacesIdInboxRouteImport.update({
    id: '/workspaces/$id/inbox',
    path: '/workspaces/$id/inbox',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedWorkspacesIdContactsRoute =
  AuthenticatedWorkspacesIdContactsRouteImport.update({
    id: '/workspaces/$id/contacts',
    path: '/workspaces/$id/contacts',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedWorkspacesIdSettingsIndexRoute =
  AuthenticatedWorkspacesIdSettingsIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedWorkspacesIdSettingsRoute,
  } as any)
const AuthenticatedWorkspacesIdInboxIndexRoute =
  AuthenticatedWorkspacesIdInboxIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedWorkspacesIdInboxRoute,
  } as any)
const AuthenticatedWorkspacesIdSettingsMembersRoute =
  AuthenticatedWorkspacesIdSettingsMembersRouteImport.update({
    id: '/members',
    path: '/members',
    getParentRoute: () => AuthenticatedWorkspacesIdSettingsRoute,
  } as any)
const AuthenticatedWorkspacesIdInboxConversationIdRoute =
  AuthenticatedWorkspacesIdInboxConversationIdRouteImport.update({
    id: '/$conversationId',
    path: '/$conversationId',
    getParentRoute: () => AuthenticatedWorkspacesIdInboxRoute,
  } as any)
const AuthenticatedWorkspacesIdSettingsChannelsIndexRoute =
  AuthenticatedWorkspacesIdSettingsChannelsIndexRouteImport.update({
    id: '/channels/',
    path: '/channels/',
    getParentRoute: () => AuthenticatedWorkspacesIdSettingsRoute,
  } as any)
const AuthenticatedWorkspacesIdSettingsChannelsNewRoute =
  AuthenticatedWorkspacesIdSettingsChannelsNewRouteImport.update({
    id: '/channels/new',
    path: '/channels/new',
    getParentRoute: () => AuthenticatedWorkspacesIdSettingsRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof AuthenticatedIndexRoute
  '/instagram-callback': typeof InstagramCallbackRoute
  '/onboarding': typeof OnboardingRoute
  '/password-reset': typeof PasswordResetRoute
  '/sign-in': typeof SignInRoute
  '/sign-up': typeof SignUpRoute
  '/profile': typeof AuthenticatedProfileRoute
  '/settings': typeof AuthenticatedSettingsRouteWithChildren
  '/settings/appearance': typeof AuthenticatedSettingsAppearanceRoute
  '/settings/notifications': typeof AuthenticatedSettingsNotificationsRoute
  '/settings/profile': typeof AuthenticatedSettingsProfileRoute
  '/settings/security': typeof AuthenticatedSettingsSecurityRoute
  '/settings/': typeof AuthenticatedSettingsIndexRoute
  '/workspaces/': typeof AuthenticatedWorkspacesIndexRoute
  '/workspaces/$id/contacts': typeof AuthenticatedWorkspacesIdContactsRoute
  '/workspaces/$id/inbox': typeof AuthenticatedWorkspacesIdInboxRouteWithChildren
  '/workspaces/$id/settings': typeof AuthenticatedWorkspacesIdSettingsRouteWithChildren
  '/workspaces/$id/': typeof AuthenticatedWorkspacesIdIndexRoute
  '/workspaces/$id/inbox/$conversationId': typeof AuthenticatedWorkspacesIdInboxConversationIdRoute
  '/workspaces/$id/settings/members': typeof AuthenticatedWorkspacesIdSettingsMembersRoute
  '/workspaces/$id/inbox/': typeof AuthenticatedWorkspacesIdInboxIndexRoute
  '/workspaces/$id/settings/': typeof AuthenticatedWorkspacesIdSettingsIndexRoute
  '/workspaces/$id/settings/channels/new': typeof AuthenticatedWorkspacesIdSettingsChannelsNewRoute
  '/workspaces/$id/settings/channels/': typeof AuthenticatedWorkspacesIdSettingsChannelsIndexRoute
}
export interface FileRoutesByTo {
  '/instagram-callback': typeof InstagramCallbackRoute
  '/onboarding': typeof OnboardingRoute
  '/password-reset': typeof PasswordResetRoute
  '/sign-in': typeof SignInRoute
  '/sign-up': typeof SignUpRoute
  '/profile': typeof AuthenticatedProfileRoute
  '/': typeof AuthenticatedIndexRoute
  '/settings/appearance': typeof AuthenticatedSettingsAppearanceRoute
  '/settings/notifications': typeof AuthenticatedSettingsNotificationsRoute
  '/settings/profile': typeof AuthenticatedSettingsProfileRoute
  '/settings/security': typeof AuthenticatedSettingsSecurityRoute
  '/settings': typeof AuthenticatedSettingsIndexRoute
  '/workspaces': typeof AuthenticatedWorkspacesIndexRoute
  '/workspaces/$id/contacts': typeof AuthenticatedWorkspacesIdContactsRoute
  '/workspaces/$id': typeof AuthenticatedWorkspacesIdIndexRoute
  '/workspaces/$id/inbox/$conversationId': typeof AuthenticatedWorkspacesIdInboxConversationIdRoute
  '/workspaces/$id/settings/members': typeof AuthenticatedWorkspacesIdSettingsMembersRoute
  '/workspaces/$id/inbox': typeof AuthenticatedWorkspacesIdInboxIndexRoute
  '/workspaces/$id/settings': typeof AuthenticatedWorkspacesIdSettingsIndexRoute
  '/workspaces/$id/settings/channels/new': typeof AuthenticatedWorkspacesIdSettingsChannelsNewRoute
  '/workspaces/$id/settings/channels': typeof AuthenticatedWorkspacesIdSettingsChannelsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/instagram-callback': typeof InstagramCallbackRoute
  '/onboarding': typeof OnboardingRoute
  '/password-reset': typeof PasswordResetRoute
  '/sign-in': typeof SignInRoute
  '/sign-up': typeof SignUpRoute
  '/_authenticated/profile': typeof AuthenticatedProfileRoute
  '/_authenticated/settings': typeof AuthenticatedSettingsRouteWithChildren
  '/_authenticated/': typeof AuthenticatedIndexRoute
  '/_authenticated/settings/appearance': typeof AuthenticatedSettingsAppearanceRoute
  '/_authenticated/settings/notifications': typeof AuthenticatedSettingsNotificationsRoute
  '/_authenticated/settings/profile': typeof AuthenticatedSettingsProfileRoute
  '/_authenticated/settings/security': typeof AuthenticatedSettingsSecurityRoute
  '/_authenticated/settings/': typeof AuthenticatedSettingsIndexRoute
  '/_authenticated/workspaces/': typeof AuthenticatedWorkspacesIndexRoute
  '/_authenticated/workspaces/$id/contacts': typeof AuthenticatedWorkspacesIdContactsRoute
  '/_authenticated/workspaces/$id/inbox': typeof AuthenticatedWorkspacesIdInboxRouteWithChildren
  '/_authenticated/workspaces/$id/settings': typeof AuthenticatedWorkspacesIdSettingsRouteWithChildren
  '/_authenticated/workspaces/$id/': typeof AuthenticatedWorkspacesIdIndexRoute
  '/_authenticated/workspaces/$id/inbox/$conversationId': typeof AuthenticatedWorkspacesIdInboxConversationIdRoute
  '/_authenticated/workspaces/$id/settings/members': typeof AuthenticatedWorkspacesIdSettingsMembersRoute
  '/_authenticated/workspaces/$id/inbox/': typeof AuthenticatedWorkspacesIdInboxIndexRoute
  '/_authenticated/workspaces/$id/settings/': typeof AuthenticatedWorkspacesIdSettingsIndexRoute
  '/_authenticated/workspaces/$id/settings/channels/new': typeof AuthenticatedWorkspacesIdSettingsChannelsNewRoute
  '/_authenticated/workspaces/$id/settings/channels/': typeof AuthenticatedWorkspacesIdSettingsChannelsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/instagram-callback'
    | '/onboarding'
    | '/password-reset'
    | '/sign-in'
    | '/sign-up'
    | '/profile'
    | '/settings'
    | '/settings/appearance'
    | '/settings/notifications'
    | '/settings/profile'
    | '/settings/security'
    | '/settings/'
    | '/workspaces/'
    | '/workspaces/$id/contacts'
    | '/workspaces/$id/inbox'
    | '/workspaces/$id/settings'
    | '/workspaces/$id/'
    | '/workspaces/$id/inbox/$conversationId'
    | '/workspaces/$id/settings/members'
    | '/workspaces/$id/inbox/'
    | '/workspaces/$id/settings/'
    | '/workspaces/$id/settings/channels/new'
    | '/workspaces/$id/settings/channels/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/instagram-callback'
    | '/onboarding'
    | '/password-reset'
    | '/sign-in'
    | '/sign-up'
    | '/profile'
    | '/'
    | '/settings/appearance'
    | '/settings/notifications'
    | '/settings/profile'
    | '/settings/security'
    | '/settings'
    | '/workspaces'
    | '/workspaces/$id/contacts'
    | '/workspaces/$id'
    | '/workspaces/$id/inbox/$conversationId'
    | '/workspaces/$id/settings/members'
    | '/workspaces/$id/inbox'
    | '/workspaces/$id/settings'
    | '/workspaces/$id/settings/channels/new'
    | '/workspaces/$id/settings/channels'
  id:
    | '__root__'
    | '/_authenticated'
    | '/instagram-callback'
    | '/onboarding'
    | '/password-reset'
    | '/sign-in'
    | '/sign-up'
    | '/_authenticated/profile'
    | '/_authenticated/settings'
    | '/_authenticated/'
    | '/_authenticated/settings/appearance'
    | '/_authenticated/settings/notifications'
    | '/_authenticated/settings/profile'
    | '/_authenticated/settings/security'
    | '/_authenticated/settings/'
    | '/_authenticated/workspaces/'
    | '/_authenticated/workspaces/$id/contacts'
    | '/_authenticated/workspaces/$id/inbox'
    | '/_authenticated/workspaces/$id/settings'
    | '/_authenticated/workspaces/$id/'
    | '/_authenticated/workspaces/$id/inbox/$conversationId'
    | '/_authenticated/workspaces/$id/settings/members'
    | '/_authenticated/workspaces/$id/inbox/'
    | '/_authenticated/workspaces/$id/settings/'
    | '/_authenticated/workspaces/$id/settings/channels/new'
    | '/_authenticated/workspaces/$id/settings/channels/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  InstagramCallbackRoute: typeof InstagramCallbackRoute
  OnboardingRoute: typeof OnboardingRoute
  PasswordResetRoute: typeof PasswordResetRoute
  SignInRoute: typeof SignInRoute
  SignUpRoute: typeof SignUpRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sign-up': {
      id: '/sign-up'
      path: '/sign-up'
      fullPath: '/sign-up'
      preLoaderRoute: typeof SignUpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sign-in': {
      id: '/sign-in'
      path: '/sign-in'
      fullPath: '/sign-in'
      preLoaderRoute: typeof SignInRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/password-reset': {
      id: '/password-reset'
      path: '/password-reset'
      fullPath: '/password-reset'
      preLoaderRoute: typeof PasswordResetRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/instagram-callback': {
      id: '/instagram-callback'
      path: '/instagram-callback'
      fullPath: '/instagram-callback'
      preLoaderRoute: typeof InstagramCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/': {
      id: '/_authenticated/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/settings': {
      id: '/_authenticated/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AuthenticatedSettingsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/profile': {
      id: '/_authenticated/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof AuthenticatedProfileRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/workspaces/': {
      id: '/_authenticated/workspaces/'
      path: '/workspaces'
      fullPath: '/workspaces/'
      preLoaderRoute: typeof AuthenticatedWorkspacesIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/settings/': {
      id: '/_authenticated/settings/'
      path: '/'
      fullPath: '/settings/'
      preLoaderRoute: typeof AuthenticatedSettingsIndexRouteImport
      parentRoute: typeof AuthenticatedSettingsRoute
    }
    '/_authenticated/settings/security': {
      id: '/_authenticated/settings/security'
      path: '/security'
      fullPath: '/settings/security'
      preLoaderRoute: typeof AuthenticatedSettingsSecurityRouteImport
      parentRoute: typeof AuthenticatedSettingsRoute
    }
    '/_authenticated/settings/profile': {
      id: '/_authenticated/settings/profile'
      path: '/profile'
      fullPath: '/settings/profile'
      preLoaderRoute: typeof AuthenticatedSettingsProfileRouteImport
      parentRoute: typeof AuthenticatedSettingsRoute
    }
    '/_authenticated/settings/notifications': {
      id: '/_authenticated/settings/notifications'
      path: '/notifications'
      fullPath: '/settings/notifications'
      preLoaderRoute: typeof AuthenticatedSettingsNotificationsRouteImport
      parentRoute: typeof AuthenticatedSettingsRoute
    }
    '/_authenticated/settings/appearance': {
      id: '/_authenticated/settings/appearance'
      path: '/appearance'
      fullPath: '/settings/appearance'
      preLoaderRoute: typeof AuthenticatedSettingsAppearanceRouteImport
      parentRoute: typeof AuthenticatedSettingsRoute
    }
    '/_authenticated/workspaces/$id/': {
      id: '/_authenticated/workspaces/$id/'
      path: '/workspaces/$id'
      fullPath: '/workspaces/$id/'
      preLoaderRoute: typeof AuthenticatedWorkspacesIdIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/workspaces/$id/settings': {
      id: '/_authenticated/workspaces/$id/settings'
      path: '/workspaces/$id/settings'
      fullPath: '/workspaces/$id/settings'
      preLoaderRoute: typeof AuthenticatedWorkspacesIdSettingsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/workspaces/$id/inbox': {
      id: '/_authenticated/workspaces/$id/inbox'
      path: '/workspaces/$id/inbox'
      fullPath: '/workspaces/$id/inbox'
      preLoaderRoute: typeof AuthenticatedWorkspacesIdInboxRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/workspaces/$id/contacts': {
      id: '/_authenticated/workspaces/$id/contacts'
      path: '/workspaces/$id/contacts'
      fullPath: '/workspaces/$id/contacts'
      preLoaderRoute: typeof AuthenticatedWorkspacesIdContactsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/workspaces/$id/settings/': {
      id: '/_authenticated/workspaces/$id/settings/'
      path: '/'
      fullPath: '/workspaces/$id/settings/'
      preLoaderRoute: typeof AuthenticatedWorkspacesIdSettingsIndexRouteImport
      parentRoute: typeof AuthenticatedWorkspacesIdSettingsRoute
    }
    '/_authenticated/workspaces/$id/inbox/': {
      id: '/_authenticated/workspaces/$id/inbox/'
      path: '/'
      fullPath: '/workspaces/$id/inbox/'
      preLoaderRoute: typeof AuthenticatedWorkspacesIdInboxIndexRouteImport
      parentRoute: typeof AuthenticatedWorkspacesIdInboxRoute
    }
    '/_authenticated/workspaces/$id/settings/members': {
      id: '/_authenticated/workspaces/$id/settings/members'
      path: '/members'
      fullPath: '/workspaces/$id/settings/members'
      preLoaderRoute: typeof AuthenticatedWorkspacesIdSettingsMembersRouteImport
      parentRoute: typeof AuthenticatedWorkspacesIdSettingsRoute
    }
    '/_authenticated/workspaces/$id/inbox/$conversationId': {
      id: '/_authenticated/workspaces/$id/inbox/$conversationId'
      path: '/$conversationId'
      fullPath: '/workspaces/$id/inbox/$conversationId'
      preLoaderRoute: typeof AuthenticatedWorkspacesIdInboxConversationIdRouteImport
      parentRoute: typeof AuthenticatedWorkspacesIdInboxRoute
    }
    '/_authenticated/workspaces/$id/settings/channels/': {
      id: '/_authenticated/workspaces/$id/settings/channels/'
      path: '/channels'
      fullPath: '/workspaces/$id/settings/channels/'
      preLoaderRoute: typeof AuthenticatedWorkspacesIdSettingsChannelsIndexRouteImport
      parentRoute: typeof AuthenticatedWorkspacesIdSettingsRoute
    }
    '/_authenticated/workspaces/$id/settings/channels/new': {
      id: '/_authenticated/workspaces/$id/settings/channels/new'
      path: '/channels/new'
      fullPath: '/workspaces/$id/settings/channels/new'
      preLoaderRoute: typeof AuthenticatedWorkspacesIdSettingsChannelsNewRouteImport
      parentRoute: typeof AuthenticatedWorkspacesIdSettingsRoute
    }
  }
}

interface AuthenticatedSettingsRouteChildren {
  AuthenticatedSettingsAppearanceRoute: typeof AuthenticatedSettingsAppearanceRoute
  AuthenticatedSettingsNotificationsRoute: typeof AuthenticatedSettingsNotificationsRoute
  AuthenticatedSettingsProfileRoute: typeof AuthenticatedSettingsProfileRoute
  AuthenticatedSettingsSecurityRoute: typeof AuthenticatedSettingsSecurityRoute
  AuthenticatedSettingsIndexRoute: typeof AuthenticatedSettingsIndexRoute
}

const AuthenticatedSettingsRouteChildren: AuthenticatedSettingsRouteChildren = {
  AuthenticatedSettingsAppearanceRoute: AuthenticatedSettingsAppearanceRoute,
  AuthenticatedSettingsNotificationsRoute:
    AuthenticatedSettingsNotificationsRoute,
  AuthenticatedSettingsProfileRoute: AuthenticatedSettingsProfileRoute,
  AuthenticatedSettingsSecurityRoute: AuthenticatedSettingsSecurityRoute,
  AuthenticatedSettingsIndexRoute: AuthenticatedSettingsIndexRoute,
}

const AuthenticatedSettingsRouteWithChildren =
  AuthenticatedSettingsRoute._addFileChildren(
    AuthenticatedSettingsRouteChildren,
  )

interface AuthenticatedWorkspacesIdInboxRouteChildren {
  AuthenticatedWorkspacesIdInboxConversationIdRoute: typeof AuthenticatedWorkspacesIdInboxConversationIdRoute
  AuthenticatedWorkspacesIdInboxIndexRoute: typeof AuthenticatedWorkspacesIdInboxIndexRoute
}

const AuthenticatedWorkspacesIdInboxRouteChildren: AuthenticatedWorkspacesIdInboxRouteChildren =
  {
    AuthenticatedWorkspacesIdInboxConversationIdRoute:
      AuthenticatedWorkspacesIdInboxConversationIdRoute,
    AuthenticatedWorkspacesIdInboxIndexRoute:
      AuthenticatedWorkspacesIdInboxIndexRoute,
  }

const AuthenticatedWorkspacesIdInboxRouteWithChildren =
  AuthenticatedWorkspacesIdInboxRoute._addFileChildren(
    AuthenticatedWorkspacesIdInboxRouteChildren,
  )

interface AuthenticatedWorkspacesIdSettingsRouteChildren {
  AuthenticatedWorkspacesIdSettingsMembersRoute: typeof AuthenticatedWorkspacesIdSettingsMembersRoute
  AuthenticatedWorkspacesIdSettingsIndexRoute: typeof AuthenticatedWorkspacesIdSettingsIndexRoute
  AuthenticatedWorkspacesIdSettingsChannelsNewRoute: typeof AuthenticatedWorkspacesIdSettingsChannelsNewRoute
  AuthenticatedWorkspacesIdSettingsChannelsIndexRoute: typeof AuthenticatedWorkspacesIdSettingsChannelsIndexRoute
}

const AuthenticatedWorkspacesIdSettingsRouteChildren: AuthenticatedWorkspacesIdSettingsRouteChildren =
  {
    AuthenticatedWorkspacesIdSettingsMembersRoute:
      AuthenticatedWorkspacesIdSettingsMembersRoute,
    AuthenticatedWorkspacesIdSettingsIndexRoute:
      AuthenticatedWorkspacesIdSettingsIndexRoute,
    AuthenticatedWorkspacesIdSettingsChannelsNewRoute:
      AuthenticatedWorkspacesIdSettingsChannelsNewRoute,
    AuthenticatedWorkspacesIdSettingsChannelsIndexRoute:
      AuthenticatedWorkspacesIdSettingsChannelsIndexRoute,
  }

const AuthenticatedWorkspacesIdSettingsRouteWithChildren =
  AuthenticatedWorkspacesIdSettingsRoute._addFileChildren(
    AuthenticatedWorkspacesIdSettingsRouteChildren,
  )

interface AuthenticatedRouteChildren {
  AuthenticatedProfileRoute: typeof AuthenticatedProfileRoute
  AuthenticatedSettingsRoute: typeof AuthenticatedSettingsRouteWithChildren
  AuthenticatedIndexRoute: typeof AuthenticatedIndexRoute
  AuthenticatedWorkspacesIndexRoute: typeof AuthenticatedWorkspacesIndexRoute
  AuthenticatedWorkspacesIdContactsRoute: typeof AuthenticatedWorkspacesIdContactsRoute
  AuthenticatedWorkspacesIdInboxRoute: typeof AuthenticatedWorkspacesIdInboxRouteWithChildren
  AuthenticatedWorkspacesIdSettingsRoute: typeof AuthenticatedWorkspacesIdSettingsRouteWithChildren
  AuthenticatedWorkspacesIdIndexRoute: typeof AuthenticatedWorkspacesIdIndexRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedProfileRoute: AuthenticatedProfileRoute,
  AuthenticatedSettingsRoute: AuthenticatedSettingsRouteWithChildren,
  AuthenticatedIndexRoute: AuthenticatedIndexRoute,
  AuthenticatedWorkspacesIndexRoute: AuthenticatedWorkspacesIndexRoute,
  AuthenticatedWorkspacesIdContactsRoute:
    AuthenticatedWorkspacesIdContactsRoute,
  AuthenticatedWorkspacesIdInboxRoute:
    AuthenticatedWorkspacesIdInboxRouteWithChildren,
  AuthenticatedWorkspacesIdSettingsRoute:
    AuthenticatedWorkspacesIdSettingsRouteWithChildren,
  AuthenticatedWorkspacesIdIndexRoute: AuthenticatedWorkspacesIdIndexRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  InstagramCallbackRoute: InstagramCallbackRoute,
  OnboardingRoute: OnboardingRoute,
  PasswordResetRoute: PasswordResetRoute,
  SignInRoute: SignInRoute,
  SignUpRoute: SignUpRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
